# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_dmg(__cs__.cstruct):
    KOLY_MAGIC: Literal[b"koly"] = ...
    MISH_MAGIC: Literal[1835627368] = ...
    ENCRCDSA_MAGIC: Literal[b"encrcdsa"] = ...
    SECTOR_SIZE: Literal[512] = ...
    class BLOCK_TYPE(__cs__.Enum):
        ZERO_FILL = ...
        RAW = ...
        IGNORE = ...
        COMMENT = ...
        ADC = ...
        ZLIB = ...
        BZLIB = ...
        LZFSE = ...
        LZMA = ...
        TERMINATOR = ...

    class UDIFChecksum(__cs__.Structure):
        Type: _c_dmg.uint32
        Size: _c_dmg.uint32
        Data: __cs__.Array[_c_dmg.uint32]
        @overload
        def __init__(
            self,
            Type: _c_dmg.uint32 | None = ...,
            Size: _c_dmg.uint32 | None = ...,
            Data: __cs__.Array[_c_dmg.uint32] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class UDIFResourceFile(__cs__.Structure):
        Signature: __cs__.CharArray
        Version: _c_dmg.uint32
        HeaderSize: _c_dmg.uint32
        Flags: _c_dmg.uint32
        RunningDataForkOffset: _c_dmg.uint64
        DataForkOffset: _c_dmg.uint64
        DataForkLength: _c_dmg.uint64
        RsrcForkOffset: _c_dmg.uint64
        RsrcForkLength: _c_dmg.uint64
        SegmentNumber: _c_dmg.uint32
        SegmentCount: _c_dmg.uint32
        SegmentID: __cs__.CharArray
        DataChecksum: _c_dmg.UDIFChecksum
        XMLOffset: _c_dmg.uint64
        XMLLength: _c_dmg.uint64
        Reserved1: __cs__.CharArray
        Checksum: _c_dmg.UDIFChecksum
        ImageVariant: _c_dmg.uint32
        SectorCount: _c_dmg.uint64
        reserved2: _c_dmg.uint32
        reserved3: _c_dmg.uint32
        reserved4: _c_dmg.uint32
        @overload
        def __init__(
            self,
            Signature: __cs__.CharArray | None = ...,
            Version: _c_dmg.uint32 | None = ...,
            HeaderSize: _c_dmg.uint32 | None = ...,
            Flags: _c_dmg.uint32 | None = ...,
            RunningDataForkOffset: _c_dmg.uint64 | None = ...,
            DataForkOffset: _c_dmg.uint64 | None = ...,
            DataForkLength: _c_dmg.uint64 | None = ...,
            RsrcForkOffset: _c_dmg.uint64 | None = ...,
            RsrcForkLength: _c_dmg.uint64 | None = ...,
            SegmentNumber: _c_dmg.uint32 | None = ...,
            SegmentCount: _c_dmg.uint32 | None = ...,
            SegmentID: __cs__.CharArray | None = ...,
            DataChecksum: _c_dmg.UDIFChecksum | None = ...,
            XMLOffset: _c_dmg.uint64 | None = ...,
            XMLLength: _c_dmg.uint64 | None = ...,
            Reserved1: __cs__.CharArray | None = ...,
            Checksum: _c_dmg.UDIFChecksum | None = ...,
            ImageVariant: _c_dmg.uint32 | None = ...,
            SectorCount: _c_dmg.uint64 | None = ...,
            reserved2: _c_dmg.uint32 | None = ...,
            reserved3: _c_dmg.uint32 | None = ...,
            reserved4: _c_dmg.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BLKXChunkEntry(__cs__.Structure):
        EntryType: _c_dmg.BLOCK_TYPE
        Comment: _c_dmg.uint32
        SectorNumber: _c_dmg.uint64
        SectorCount: _c_dmg.uint64
        CompressedOffset: _c_dmg.uint64
        CompressedLength: _c_dmg.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_dmg.BLOCK_TYPE | None = ...,
            Comment: _c_dmg.uint32 | None = ...,
            SectorNumber: _c_dmg.uint64 | None = ...,
            SectorCount: _c_dmg.uint64 | None = ...,
            CompressedOffset: _c_dmg.uint64 | None = ...,
            CompressedLength: _c_dmg.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BLKXTable(__cs__.Structure):
        Signature: _c_dmg.uint32
        Version: _c_dmg.uint32
        SectorNumber: _c_dmg.uint64
        SectorCount: _c_dmg.uint64
        DataOffset: _c_dmg.uint64
        BuffersNeeded: _c_dmg.uint32
        BlockDescriptors: _c_dmg.uint32
        reserved1: _c_dmg.uint32
        reserved2: _c_dmg.uint32
        reserved3: _c_dmg.uint32
        reserved4: _c_dmg.uint32
        reserved5: _c_dmg.uint32
        reserved6: _c_dmg.uint32
        checksum: _c_dmg.UDIFChecksum
        NumberOfBlockChunks: _c_dmg.uint32
        class BLKXChunkEntry(__cs__.Structure):
            EntryType: _c_dmg.BLOCK_TYPE
            Comment: _c_dmg.uint32
            SectorNumber: _c_dmg.uint64
            SectorCount: _c_dmg.uint64
            CompressedOffset: _c_dmg.uint64
            CompressedLength: _c_dmg.uint64
            @overload
            def __init__(
                self,
                EntryType: _c_dmg.BLOCK_TYPE | None = ...,
                Comment: _c_dmg.uint32 | None = ...,
                SectorNumber: _c_dmg.uint64 | None = ...,
                SectorCount: _c_dmg.uint64 | None = ...,
                CompressedOffset: _c_dmg.uint64 | None = ...,
                CompressedLength: _c_dmg.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        Entries: __cs__.Array[BLKXChunkEntry]
        @overload
        def __init__(
            self,
            Signature: _c_dmg.uint32 | None = ...,
            Version: _c_dmg.uint32 | None = ...,
            SectorNumber: _c_dmg.uint64 | None = ...,
            SectorCount: _c_dmg.uint64 | None = ...,
            DataOffset: _c_dmg.uint64 | None = ...,
            BuffersNeeded: _c_dmg.uint32 | None = ...,
            BlockDescriptors: _c_dmg.uint32 | None = ...,
            reserved1: _c_dmg.uint32 | None = ...,
            reserved2: _c_dmg.uint32 | None = ...,
            reserved3: _c_dmg.uint32 | None = ...,
            reserved4: _c_dmg.uint32 | None = ...,
            reserved5: _c_dmg.uint32 | None = ...,
            reserved6: _c_dmg.uint32 | None = ...,
            checksum: _c_dmg.UDIFChecksum | None = ...,
            NumberOfBlockChunks: _c_dmg.uint32 | None = ...,
            Entries: __cs__.Array[BLKXChunkEntry] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class EncrcdsaHeader(__cs__.Structure):
        Signature: __cs__.CharArray
        Version: _c_dmg.uint32
        BlockIVSize: _c_dmg.uint32
        EncryptionMode: _c_dmg.uint32
        EncryptionAlgorithm: _c_dmg.uint32
        KeyBits: _c_dmg.uint32
        PRNGAlgorithm: _c_dmg.uint32
        PRNGKeyBits: _c_dmg.uint32
        UUID: __cs__.CharArray
        BlockSize: _c_dmg.uint32
        DataSize: _c_dmg.uint64
        DataOffset: _c_dmg.uint64
        KeyCount: _c_dmg.uint32
        @overload
        def __init__(
            self,
            Signature: __cs__.CharArray | None = ...,
            Version: _c_dmg.uint32 | None = ...,
            BlockIVSize: _c_dmg.uint32 | None = ...,
            EncryptionMode: _c_dmg.uint32 | None = ...,
            EncryptionAlgorithm: _c_dmg.uint32 | None = ...,
            KeyBits: _c_dmg.uint32 | None = ...,
            PRNGAlgorithm: _c_dmg.uint32 | None = ...,
            PRNGKeyBits: _c_dmg.uint32 | None = ...,
            UUID: __cs__.CharArray | None = ...,
            BlockSize: _c_dmg.uint32 | None = ...,
            DataSize: _c_dmg.uint64 | None = ...,
            DataOffset: _c_dmg.uint64 | None = ...,
            KeyCount: _c_dmg.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class EncrcdsaKeyPointer(__cs__.Structure):
        Type: _c_dmg.uint32
        _reserved1: _c_dmg.uint32
        Offset: _c_dmg.uint32
        _reserved2: _c_dmg.uint32
        Size: _c_dmg.uint32
        @overload
        def __init__(
            self,
            Type: _c_dmg.uint32 | None = ...,
            _reserved1: _c_dmg.uint32 | None = ...,
            Offset: _c_dmg.uint32 | None = ...,
            _reserved2: _c_dmg.uint32 | None = ...,
            Size: _c_dmg.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class EncrcdsaKeyBlob(__cs__.Structure):
        KDFAlgorithm: _c_dmg.uint32
        KDFIterationCount: _c_dmg.uint64
        KDFSaltLen: _c_dmg.uint32
        KDFSalt: __cs__.CharArray
        BlobEncIVSize: _c_dmg.uint32
        BlobEncIV: __cs__.CharArray
        BlobEncKeyBits: _c_dmg.uint32
        BlobEncAlgorithm: _c_dmg.uint32
        BlobEncPadding: _c_dmg.uint32
        BlobEncMode: _c_dmg.uint32
        EncryptedKeyblobSize: _c_dmg.uint32
        EncryptedKeyblob: __cs__.CharArray
        @overload
        def __init__(
            self,
            KDFAlgorithm: _c_dmg.uint32 | None = ...,
            KDFIterationCount: _c_dmg.uint64 | None = ...,
            KDFSaltLen: _c_dmg.uint32 | None = ...,
            KDFSalt: __cs__.CharArray | None = ...,
            BlobEncIVSize: _c_dmg.uint32 | None = ...,
            BlobEncIV: __cs__.CharArray | None = ...,
            BlobEncKeyBits: _c_dmg.uint32 | None = ...,
            BlobEncAlgorithm: _c_dmg.uint32 | None = ...,
            BlobEncPadding: _c_dmg.uint32 | None = ...,
            BlobEncMode: _c_dmg.uint32 | None = ...,
            EncryptedKeyblobSize: _c_dmg.uint32 | None = ...,
            EncryptedKeyblob: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_dmg` is an instance of `_c_dmg`, but then we can't use it in type hints
c_dmg: TypeAlias = _c_dmg
