# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_vmdk(__cs__.cstruct):
    SPARSE_MAGICNUMBER: Literal[1447904331] = ...
    SPARSE_VERSION_INCOMPAT_FLAGS: Literal[3] = ...
    SPARSE_GTE_EMPTY: Literal[0] = ...
    SPARSE_GD_AT_END: Literal[18446744073709551615] = ...
    SPARSE_SINGLE_END_LINE_CHAR: Literal["'"] = ...
    SPARSE_NON_END_LINE_CHAR: Literal[" "] = ...
    SPARSE_DOUBLE_END_LINE_CHAR1: Literal["'"] = ...
    SPARSE_DOUBLE_END_LINE_CHAR2: Literal["'"] = ...
    SPARSEFLAG_COMPAT_FLAGS: Literal[65535] = ...
    SPARSEFLAG_VALID_NEWLINE_DETECTOR: Literal[1] = ...
    SPARSEFLAG_USE_REDUNDANT: Literal[2] = ...
    SPARSEFLAG_MAGIC_GTE: Literal[4] = ...
    SPARSEFLAG_INCOMPAT_FLAGS: Literal[4294901760] = ...
    SPARSEFLAG_COMPRESSED: Literal[65536] = ...
    SPARSEFLAG_EMBEDDED_LBA: Literal[131072] = ...
    SPARSE_COMPRESSALGORITHM_NONE: Literal[0] = ...
    SPARSE_COMPRESSALGORITHM_DEFLATE: Literal[1] = ...
    GRAIN_MARKER_EOS: Literal[0] = ...
    GRAIN_MARKER_GRAIN_TABLE: Literal[1] = ...
    GRAIN_MARKER_GRAIN_DIRECTORY: Literal[2] = ...
    GRAIN_MARKER_FOOTER: Literal[3] = ...
    GRAIN_MARKER_PROGRESS: Literal[4] = ...
    COWDISK_MAX_PARENT_FILELEN: Literal[1024] = ...
    COWDISK_MAX_NAME_LEN: Literal[60] = ...
    COWDISK_MAX_DESC_LEN: Literal[512] = ...
    COWDISK_MAGIC: Literal[1146572611] = ...
    COWDISK_ROOT: Literal[1] = ...
    COWDISK_CHECKCAPABLE: Literal[2] = ...
    COWDISK_INCONSISTENT: Literal[4] = ...
    SESPARSE_CONST_HEADER_MAGIC: Literal[3405691582] = ...
    SESPARSE_VOLATILE_HEADER_MAGIC: Literal[3405691582] = ...
    SESPARSE_GRAIN_TYPE_MASK: Literal[17293822569102704640] = ...
    SESPARSE_GRAIN_TYPE_UNALLOCATED: Literal[0] = ...
    SESPARSE_GRAIN_TYPE_FALLTHROUGH: Literal[1152921504606846976] = ...
    SESPARSE_GRAIN_TYPE_ZERO: Literal[2305843009213693952] = ...
    SESPARSE_GRAIN_TYPE_ALLOCATED: Literal[3458764513820540928] = ...
    class SparseExtentHeader(__cs__.Structure):
        magicNumber: _c_vmdk.uint32
        version: _c_vmdk.uint32
        flags: _c_vmdk.uint32
        capacity: _c_vmdk.uint64
        grainSize: _c_vmdk.uint64
        descriptorOffset: _c_vmdk.uint64
        descriptorSize: _c_vmdk.uint64
        numGTEsPerGT: _c_vmdk.uint32
        rgdOffset: _c_vmdk.uint64
        gdOffset: _c_vmdk.uint64
        overHead: _c_vmdk.uint64
        uncleanShutdown: _c_vmdk.uint8
        singleEndLineChar: _c_vmdk.char
        nonEndLineChar: _c_vmdk.char
        doubleEndLineChar1: _c_vmdk.char
        doubleEndLineChar2: _c_vmdk.char
        compressAlgorithm: _c_vmdk.uint16
        pad: __cs__.CharArray
        @overload
        def __init__(
            self,
            magicNumber: _c_vmdk.uint32 | None = ...,
            version: _c_vmdk.uint32 | None = ...,
            flags: _c_vmdk.uint32 | None = ...,
            capacity: _c_vmdk.uint64 | None = ...,
            grainSize: _c_vmdk.uint64 | None = ...,
            descriptorOffset: _c_vmdk.uint64 | None = ...,
            descriptorSize: _c_vmdk.uint64 | None = ...,
            numGTEsPerGT: _c_vmdk.uint32 | None = ...,
            rgdOffset: _c_vmdk.uint64 | None = ...,
            gdOffset: _c_vmdk.uint64 | None = ...,
            overHead: _c_vmdk.uint64 | None = ...,
            uncleanShutdown: _c_vmdk.uint8 | None = ...,
            singleEndLineChar: _c_vmdk.char | None = ...,
            nonEndLineChar: _c_vmdk.char | None = ...,
            doubleEndLineChar1: _c_vmdk.char | None = ...,
            doubleEndLineChar2: _c_vmdk.char | None = ...,
            compressAlgorithm: _c_vmdk.uint16 | None = ...,
            pad: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SparseGrainLBAHeader(__cs__.Structure):
        lba: _c_vmdk.uint64
        cmpSize: _c_vmdk.uint32
        @overload
        def __init__(self, lba: _c_vmdk.uint64 | None = ..., cmpSize: _c_vmdk.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SparseSpecialLBAHeader(__cs__.Structure):
        lba: _c_vmdk.uint64
        cmpSize: _c_vmdk.uint32
        type: _c_vmdk.uint32
        @overload
        def __init__(
            self,
            lba: _c_vmdk.uint64 | None = ...,
            cmpSize: _c_vmdk.uint32 | None = ...,
            type: _c_vmdk.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SparseMetaDataMarker(__cs__.Structure):
        numSectors: _c_vmdk.uint64
        size: _c_vmdk.uint32
        type: _c_vmdk.uint32
        pad: __cs__.CharArray
        metadata: __cs__.CharArray
        @overload
        def __init__(
            self,
            numSectors: _c_vmdk.uint64 | None = ...,
            size: _c_vmdk.uint32 | None = ...,
            type: _c_vmdk.uint32 | None = ...,
            pad: __cs__.CharArray | None = ...,
            metadata: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class COWDisk_Header(__cs__.Structure):
        magicNumber: _c_vmdk.uint32
        version: _c_vmdk.uint32
        flags: _c_vmdk.uint32
        numSectors: _c_vmdk.uint32
        grainSize: _c_vmdk.uint32
        gdOffset: _c_vmdk.uint32
        numGDEntries: _c_vmdk.uint32
        freeSector: _c_vmdk.uint32
        class __anonymous_5__(__cs__.Union):
            class __anonymous_3__(__cs__.Structure):
                cylinders: _c_vmdk.uint32
                heads: _c_vmdk.uint32
                sectors: _c_vmdk.uint32
                @overload
                def __init__(
                    self,
                    cylinders: _c_vmdk.uint32 | None = ...,
                    heads: _c_vmdk.uint32 | None = ...,
                    sectors: _c_vmdk.uint32 | None = ...,
                ): ...
                @overload
                def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

            root: __anonymous_3__
            class __anonymous_4__(__cs__.Structure):
                parentFileName: __cs__.CharArray
                parentGeneration: _c_vmdk.uint32
                @overload
                def __init__(
                    self, parentFileName: __cs__.CharArray | None = ..., parentGeneration: _c_vmdk.uint32 | None = ...
                ): ...
                @overload
                def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

            child: __anonymous_4__
            @overload
            def __init__(self, root: __anonymous_3__ | None = ..., child: __anonymous_4__ | None = ...): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        u: __anonymous_5__
        generation: _c_vmdk.uint32
        name: __cs__.CharArray
        description: __cs__.CharArray
        savedGeneration: _c_vmdk.uint32
        reserved: __cs__.CharArray
        uncleanShutdown: _c_vmdk.uint32
        padding: __cs__.CharArray
        @overload
        def __init__(
            self,
            magicNumber: _c_vmdk.uint32 | None = ...,
            version: _c_vmdk.uint32 | None = ...,
            flags: _c_vmdk.uint32 | None = ...,
            numSectors: _c_vmdk.uint32 | None = ...,
            grainSize: _c_vmdk.uint32 | None = ...,
            gdOffset: _c_vmdk.uint32 | None = ...,
            numGDEntries: _c_vmdk.uint32 | None = ...,
            freeSector: _c_vmdk.uint32 | None = ...,
            u: __anonymous_5__ | None = ...,
            generation: _c_vmdk.uint32 | None = ...,
            name: __cs__.CharArray | None = ...,
            description: __cs__.CharArray | None = ...,
            savedGeneration: _c_vmdk.uint32 | None = ...,
            reserved: __cs__.CharArray | None = ...,
            uncleanShutdown: _c_vmdk.uint32 | None = ...,
            padding: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SESparseExtent(__cs__.Structure):
        offset: _c_vmdk.uint64
        size: _c_vmdk.uint64
        @overload
        def __init__(self, offset: _c_vmdk.uint64 | None = ..., size: _c_vmdk.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SESparseConstHeader(__cs__.Structure):
        constMagic: _c_vmdk.uint64
        version: _c_vmdk.uint64
        capacity: _c_vmdk.uint64
        grainSize: _c_vmdk.uint64
        grainTableSize: _c_vmdk.uint64
        flags: _c_vmdk.uint64
        reserved1: _c_vmdk.uint64
        reserved2: _c_vmdk.uint64
        reserved3: _c_vmdk.uint64
        reserved4: _c_vmdk.uint64
        volatileHeader: _c_vmdk.SESparseExtent
        journalHeader: _c_vmdk.SESparseExtent
        journal: _c_vmdk.SESparseExtent
        grainDirectory: _c_vmdk.SESparseExtent
        grainTables: _c_vmdk.SESparseExtent
        freeBitmap: _c_vmdk.SESparseExtent
        backMap: _c_vmdk.SESparseExtent
        grain: _c_vmdk.SESparseExtent
        pad: __cs__.CharArray
        @overload
        def __init__(
            self,
            constMagic: _c_vmdk.uint64 | None = ...,
            version: _c_vmdk.uint64 | None = ...,
            capacity: _c_vmdk.uint64 | None = ...,
            grainSize: _c_vmdk.uint64 | None = ...,
            grainTableSize: _c_vmdk.uint64 | None = ...,
            flags: _c_vmdk.uint64 | None = ...,
            reserved1: _c_vmdk.uint64 | None = ...,
            reserved2: _c_vmdk.uint64 | None = ...,
            reserved3: _c_vmdk.uint64 | None = ...,
            reserved4: _c_vmdk.uint64 | None = ...,
            volatileHeader: _c_vmdk.SESparseExtent | None = ...,
            journalHeader: _c_vmdk.SESparseExtent | None = ...,
            journal: _c_vmdk.SESparseExtent | None = ...,
            grainDirectory: _c_vmdk.SESparseExtent | None = ...,
            grainTables: _c_vmdk.SESparseExtent | None = ...,
            freeBitmap: _c_vmdk.SESparseExtent | None = ...,
            backMap: _c_vmdk.SESparseExtent | None = ...,
            grain: _c_vmdk.SESparseExtent | None = ...,
            pad: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SESparseVolatileHeader(__cs__.Structure):
        volatileMagic: _c_vmdk.uint64
        freeGTNumber: _c_vmdk.uint64
        nextTxnSeqNumber: _c_vmdk.uint64
        replayJournal: _c_vmdk.uint64
        pad: __cs__.CharArray
        @overload
        def __init__(
            self,
            volatileMagic: _c_vmdk.uint64 | None = ...,
            freeGTNumber: _c_vmdk.uint64 | None = ...,
            nextTxnSeqNumber: _c_vmdk.uint64 | None = ...,
            replayJournal: _c_vmdk.uint64 | None = ...,
            pad: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_vmdk` is an instance of `_c_vmdk`, but then we can't use it in type hints
c_vmdk: TypeAlias = _c_vmdk

SPARSE_MAGIC: bytes
COWD_MAGIC: bytes
SESPARSE_MAGIC: bytes
